const BASE_FEED_TOPICS = [
  {
    id: 'hydration-habits',
    lifestyleCategory: 'everyday_wellness',
    storyCategory: 'everyday_wellness',
    titleConcept: 'hydration habits',
    searchConcepts: ['daily hydration habits', 'fluid intake wellness'],
    excludedConcepts: ['hydrogel', 'polycyclic aromatic', 'nanoclay', 'wastewater'],
    preferredSourceTypes: ['pubmed', 'openfda_food'],
    minimumSourceQuality: 0.45,
    freshnessWindowDays: 730,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'everyday_wellness',
  },
  {
    id: 'sleep-recovery',
    lifestyleCategory: 'everyday_wellness',
    storyCategory: 'everyday_wellness',
    titleConcept: 'sleep and recovery routines',
    searchConcepts: ['sleep hygiene habits', 'recovery routines wellness'],
    excludedConcepts: ['hydrogel', 'industrial', 'polymer'],
    preferredSourceTypes: ['pubmed'],
    minimumSourceQuality: 0.5,
    freshnessWindowDays: 1095,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'everyday_wellness',
  },
  {
    id: 'supplement-literacy',
    lifestyleCategory: 'ingredient_spotlight',
    storyCategory: 'ingredient_spotlight',
    titleConcept: 'supplement label literacy',
    searchConcepts: ['dietary supplement label reading', 'supplement facts panel'],
    excludedConcepts: ['industrial chemistry'],
    preferredSourceTypes: ['pubmed', 'openfda_drug'],
    minimumSourceQuality: 0.5,
    freshnessWindowDays: 1825,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'supplement_literacy',
  },
  {
    id: 'claims-decoded-natural',
    lifestyleCategory: 'claims_decoded',
    storyCategory: 'claims_decoded',
    titleConcept: 'natural and clean label claims',
    searchConcepts: ['natural label claims food marketing', 'clean label consumer understanding'],
    excludedConcepts: ['hydrogel', 'materials science'],
    preferredSourceTypes: ['pubmed'],
    minimumSourceQuality: 0.45,
    freshnessWindowDays: 1825,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'claims_decoded',
  },
  {
    id: 'otc-label-literacy',
    lifestyleCategory: 'medicine_cabinet',
    storyCategory: 'medicine_cabinet',
    titleConcept: 'reading OTC medicine labels',
    searchConcepts: ['over the counter medication label warnings', 'active ingredient duplication OTC'],
    excludedConcepts: ['industrial'],
    preferredSourceTypes: ['openfda_drug', 'pubmed'],
    minimumSourceQuality: 0.5,
    freshnessWindowDays: 1825,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'medicine_cabinet',
  },
  {
    id: 'functional-drinks-trend',
    lifestyleCategory: 'product_trends',
    storyCategory: 'product_trends',
    titleConcept: 'functional drinks and wellness beverages',
    searchConcepts: ['functional beverage trends', 'electrolyte drink wellness'],
    excludedConcepts: ['hydrogel', 'nanoclay', 'drinking water analysis laboratory'],
    preferredSourceTypes: ['pubmed'],
    minimumSourceQuality: 0.45,
    freshnessWindowDays: 365,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'trends',
  },
  {
    id: 'seasonal-wellness',
    lifestyleCategory: 'everyday_wellness',
    storyCategory: 'everyday_wellness',
    titleConcept: 'seasonal wellness routines',
    searchConcepts: ['seasonal wellness habits', 'winter wellness routines'],
    excludedConcepts: ['industrial'],
    preferredSourceTypes: ['pubmed'],
    minimumSourceQuality: 0.4,
    freshnessWindowDays: 730,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'everyday_wellness',
  },
  {
    id: 'general-food-safety',
    lifestyleCategory: 'safety_and_recalls',
    storyCategory: 'safety_and_recalls',
    titleConcept: 'recent food safety updates',
    searchConcepts: ['food recall', 'undeclared allergen recall'],
    excludedConcepts: [],
    preferredSourceTypes: ['openfda_food'],
    minimumSourceQuality: 0.55,
    freshnessWindowDays: 60,
    aiSummarizationAllowed: true,
    generalFeedEligible: true,
    targetMix: 'safety',
  },
];

const BASE_FEED_MIX_TARGETS = {
  everyday_wellness: 2,
  ingredient_or_trend: 1,
  claims_decoded: 1,
  safety: 1,
  medicine_cabinet_or_supplement: 1,
};

function getBaseTopicsForMix() {
  return BASE_FEED_TOPICS.filter((topic) => topic.generalFeedEligible);
}

function getTopicById(topicId) {
  return BASE_FEED_TOPICS.find((topic) => topic.id === topicId) || null;
}

module.exports = {
  BASE_FEED_TOPICS,
  BASE_FEED_MIX_TARGETS,
  getBaseTopicsForMix,
  getTopicById,
};
